import type { ApiFormat, ProviderEndpoint, Transport } from "./slots";

const t = (
  formats: ApiFormat[],
  baseUrl: string,
  supportsModelsEndpoint = false,
): Transport => ({
  formats: new Set(formats),
  baseUrl,
  supportsModelsEndpoint,
});

export const ENDPOINTS: ProviderEndpoint[] = [
  {
    id: "anthropic",
    name: "Claude Official",
    category: "official",
    transport: t(["anthropic"], ""),
    icon: "anthropic",
    iconColor: "#D4915D",
    websiteUrl: "https://www.anthropic.com/claude-code",
  },
  {
    id: "openai",
    name: "OpenAI Official",
    category: "official",
    transport: t(["openai_chat", "openai_responses"], ""),
    icon: "openai",
    iconColor: "#00A67E",
    websiteUrl: "https://chatgpt.com/codex",
  },
  {
    id: "google",
    name: "Google Official",
    category: "official",
    transport: t(["google"], ""),
    icon: "gemini",
    iconColor: "#4285F4",
    websiteUrl: "https://ai.google.dev/",
  },
  {
    id: "azure",
    name: "Azure OpenAI",
    category: "official",
    transport: t(
      ["openai_responses"],
      "https://YOUR_RESOURCE.openai.azure.com/openai",
    ),
    icon: "azure",
    iconColor: "#0078D4",
    websiteUrl:
      "https://learn.microsoft.com/azure/ai-foundry/openai/how-to/codex",
  },

  {
    id: "deepseek",
    name: "DeepSeek",
    category: "cn_official",
    transport: t(
      ["anthropic", "openai_chat"],
      "https://api.deepseek.com",
      true,
    ),
    icon: "deepseek",
    iconColor: "#1E88E5",
    websiteUrl: "https://platform.deepseek.com",
    apiKeyUrl: "https://platform.deepseek.com/api_keys",
  },
  {
    id: "zhipu",
    name: "Zhipu GLM",
    category: "cn_official",
    transport: t(
      ["anthropic", "openai_chat"],
      "https://open.bigmodel.cn/api/paas/v4",
      true,
    ),
    icon: "zhipu",
    iconColor: "#0F62FE",
    websiteUrl: "https://open.bigmodel.cn",
    apiKeyUrl: "https://www.bigmodel.cn/claude-code?ic=RRVJPB5SII",
    isPartner: true,
    partnerPromotionKey: "zhipu",
  },
  {
    id: "zhipu_en",
    name: "Zhipu GLM en",
    category: "cn_official",
    transport: t(["anthropic", "openai_chat"], "https://api.z.ai/v1", true),
    icon: "zhipu",
    iconColor: "#0F62FE",
    websiteUrl: "https://z.ai",
    apiKeyUrl: "https://z.ai/subscribe?ic=8JVLJQFSKB",
    isPartner: true,
    partnerPromotionKey: "zhipu",
  },
  {
    id: "bailian",
    name: "Bailian",
    category: "cn_official",
    transport: t(
      ["anthropic", "openai_chat"],
      "https://dashscope.aliyuncs.com/compatible-mode/v1",
    ),
    icon: "bailian",
    iconColor: "#624AFF",
    websiteUrl: "https://bailian.console.aliyun.com",
  },
  {
    id: "kimi",
    name: "Kimi k2.5",
    category: "cn_official",
    transport: t(
      ["anthropic", "openai_chat"],
      "https://api.moonshot.cn/v1",
      true,
    ),
    icon: "kimi",
    iconColor: "#6366F1",
    websiteUrl: "https://platform.moonshot.cn/console",
    apiKeyUrl: "https://platform.moonshot.cn/console/api-keys",
  },
  {
    id: "kimi_coding",
    name: "Kimi For Coding",
    category: "cn_official",
    transport: t(["anthropic", "openai_chat"], "https://api.kimi.com/v1"),
    icon: "kimi",
    iconColor: "#6366F1",
    websiteUrl: "https://www.kimi.com/coding/docs/",
  },
  {
    id: "minimax",
    name: "MiniMax",
    category: "cn_official",
    transport: t(["anthropic", "openai_chat"], "https://api.minimaxi.com/v1"),
    icon: "minimax",
    iconColor: "#FF6B6B",
    websiteUrl: "https://platform.minimaxi.com",
    apiKeyUrl: "https://platform.minimaxi.com/subscribe/coding-plan",
    isPartner: true,
    partnerPromotionKey: "minimax_cn",
  },
  {
    id: "minimax_en",
    name: "MiniMax en",
    category: "cn_official",
    transport: t(["anthropic", "openai_chat"], "https://api.minimax.io/v1"),
    icon: "minimax",
    iconColor: "#FF6B6B",
    websiteUrl: "https://platform.minimax.io",
    apiKeyUrl: "https://platform.minimax.io/subscribe/coding-plan",
    isPartner: true,
    partnerPromotionKey: "minimax_en",
  },
  {
    id: "doubao",
    name: "DouBaoSeed",
    category: "cn_official",
    transport: t(
      ["anthropic", "openai_chat"],
      "https://ark.cn-beijing.volces.com/api/v3",
    ),
    icon: "doubao",
    iconColor: "#3370FF",
    websiteUrl: "https://www.volcengine.com/product/doubao",
  },
  {
    id: "bailing",
    name: "BaiLing",
    category: "cn_official",
    transport: t(["anthropic", "openai_chat"], "https://api.tbox.cn/v1"),
    websiteUrl: "https://alipaytbox.yuque.com/sxs0ba/ling/get_started",
  },
  {
    id: "katcoder",
    name: "KAT-Coder",
    category: "cn_official",
    transport: t(
      ["anthropic", "openai_chat"],
      "https://vanchin.streamlake.ai/api/gateway/v1/endpoints/${ENDPOINT_ID}",
    ),
    icon: "catcoder",
    websiteUrl: "https://console.streamlake.ai",
    apiKeyUrl: "https://console.streamlake.ai/console/api-key",
  },
  {
    id: "longcat",
    name: "Longcat",
    category: "cn_official",
    transport: t(["anthropic", "openai_chat"], "https://api.longcat.chat/v1"),
    icon: "longcat",
    iconColor: "#29E154",
    websiteUrl: "https://longcat.chat/platform",
    apiKeyUrl: "https://longcat.chat/platform/api_keys",
  },
  {
    id: "mimo",
    name: "Xiaomi MiMo",
    category: "cn_official",
    transport: t(["anthropic", "openai_chat"], "https://api.xiaomimimo.com/v1"),
    icon: "xiaomimimo",
    iconColor: "#000000",
    websiteUrl: "https://platform.xiaomimimo.com",
    apiKeyUrl: "https://platform.xiaomimimo.com/#/console/api-keys",
  },

  {
    id: "opencode_zen",
    name: "OpenCode Zen",
    category: "aggregator",
    transport: t(
      ["anthropic", "openai_chat", "openai_responses", "google"],
      "https://opencode.ai/zen/v1",
      true,
    ),
    icon: "opencode",
    iconColor: "#211E1E",
    websiteUrl: "https://opencode.ai/docs/",
    apiKeyUrl: "https://opencode.ai/docs/",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    category: "aggregator",
    transport: t(
      ["anthropic", "openai_chat", "openai_responses", "google"],
      "https://openrouter.ai/api/v1",
      true,
    ),
    icon: "openrouter",
    iconColor: "#6566F1",
    websiteUrl: "https://openrouter.ai",
    apiKeyUrl: "https://openrouter.ai/keys",
  },
  {
    id: "aihubmix",
    name: "AiHubMix",
    category: "aggregator",
    transport: t(
      ["anthropic", "openai_responses"],
      "https://aihubmix.com",
      true,
    ),
    icon: "aihubmix",
    iconColor: "#006FFB",
    websiteUrl: "https://aihubmix.com",
  },
  {
    id: "dmxapi",
    name: "DMXAPI",
    category: "aggregator",
    transport: t(
      ["anthropic", "openai_responses"],
      "https://www.dmxapi.cn",
      true,
    ),
    websiteUrl: "https://www.dmxapi.cn",
    isPartner: true,
    partnerPromotionKey: "dmxapi",
  },
  {
    id: "siliconflow",
    name: "SiliconFlow",
    category: "aggregator",
    transport: t(
      ["anthropic", "openai_chat"],
      "https://api.siliconflow.cn/v1",
      true,
    ),
    icon: "siliconflow",
    iconColor: "#6E29F6",
    websiteUrl: "https://siliconflow.cn",
    apiKeyUrl: "https://cloud.siliconflow.cn/me/account/ak",
  },
  {
    id: "siliconflow_en",
    name: "SiliconFlow en",
    category: "aggregator",
    transport: t(
      ["anthropic", "openai_chat"],
      "https://api.siliconflow.com/v1",
      true,
    ),
    icon: "siliconflow",
    iconColor: "#000000",
    websiteUrl: "https://siliconflow.com",
    apiKeyUrl: "https://cloud.siliconflow.com/account/ak",
  },
  {
    id: "modelscope",
    name: "ModelScope",
    category: "aggregator",
    transport: t(
      ["anthropic", "openai_chat"],
      "https://api-inference.modelscope.cn/v1",
    ),
    icon: "modelscope",
    iconColor: "#624AFF",
    websiteUrl: "https://modelscope.cn",
    apiKeyUrl: "https://modelscope.cn/my/myaccesstoken",
  },
  {
    id: "nvidia",
    name: "Nvidia",
    category: "aggregator",
    transport: t(["openai_chat"], "https://integrate.api.nvidia.com/v1", true),
    icon: "nvidia",
    iconColor: "#000000",
    websiteUrl: "https://build.nvidia.com",
    apiKeyUrl: "https://build.nvidia.com/settings/api-keys",
  },
  {
    id: "nebius",
    name: "Nebius",
    category: "aggregator",
    transport: t(["openai_chat"], "https://api.studio.nebius.ai/v1", true),
    websiteUrl: "https://nebius.com",
    apiKeyUrl: "https://tokenfactory.nebius.com",
  },
  {
    id: "kilo",
    name: "Kilo.ai",
    category: "aggregator",
    transport: t(["openai_chat"], "https://api.kilo.ai/api/gateway"),
    icon: "openai",
    iconColor: "#000000",
    websiteUrl: "https://kilo.ai",
    apiKeyUrl: "https://kilo.ai/docs/gateway/authentication",
  },

  {
    id: "packycode",
    name: "PackyCode",
    category: "partner",
    transport: t(
      ["anthropic", "openai_responses", "google"],
      "https://www.packyapi.com",
      true,
    ),
    icon: "packycode",
    websiteUrl: "https://www.packyapi.com",
    apiKeyUrl: "https://www.packyapi.com/register?aff=cc-switch",
    isPartner: true,
    partnerPromotionKey: "packycode",
  },
  {
    id: "cubence",
    name: "Cubence",
    category: "partner",
    transport: t(
      ["anthropic", "openai_responses", "google"],
      "https://api.cubence.com",
      true,
    ),
    icon: "cubence",
    iconColor: "#000000",
    websiteUrl: "https://cubence.com",
    apiKeyUrl: "https://cubence.com/signup?code=CCSWITCH&source=ccs",
    isPartner: true,
    partnerPromotionKey: "cubence",
  },
  {
    id: "aigocode",
    name: "AIGoCode",
    category: "partner",
    transport: t(
      ["anthropic", "openai_responses", "google"],
      "https://api.aigocode.com",
      true,
    ),
    icon: "aigocode",
    iconColor: "#5B7FFF",
    websiteUrl: "https://aigocode.com",
    apiKeyUrl: "https://aigocode.com/invite/CC-SWITCH",
    isPartner: true,
    partnerPromotionKey: "aigocode",
  },
  {
    id: "rightcode",
    name: "RightCode",
    category: "partner",
    transport: t(
      ["anthropic", "openai_chat", "openai_responses"],
      "https://right.codes/codex/v1",
    ),
    icon: "rc",
    iconColor: "#E96B2C",
    websiteUrl: "https://www.right.codes",
    apiKeyUrl: "https://www.right.codes/register?aff=CCSWITCH",
    isPartner: true,
    partnerPromotionKey: "rightcode",
  },
  {
    id: "aicodemirror",
    name: "AICodeMirror",
    category: "partner",
    transport: t(
      ["anthropic", "openai_responses", "google"],
      "https://api.aicodemirror.com/api/claudecode",
      true,
    ),
    icon: "aicodemirror",
    iconColor: "#000000",
    websiteUrl: "https://www.aicodemirror.com",
    apiKeyUrl: "https://www.aicodemirror.com/register?invitecode=9915W3",
    isPartner: true,
    partnerPromotionKey: "aicodemirror",
  },
];

export const BY_ID = new Map(ENDPOINTS.map((e) => [e.id, e]));
